/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;
import Modelo.Pelicula;
import Persistencia.PeliculaData;
import java.awt.Graphics;
import java.awt.Image;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author chich
 */
public class Peliculas extends javax.swing.JInternalFrame {
 DefaultTableModel modelo = new DefaultTableModel();
 private PeliculaData  peliculaData;   
    /**
     * Creates new form Peliculas
     */
    public Peliculas() {
        
        initComponents();
        peliculaData = new PeliculaData();
        modelo = (DefaultTableModel) TablaPelicula.getModel();
        cargarComboPeliculas();
        cargarPeliculasEnTabla();
        
        Buscar.addActionListener(e -> buscarPelicula());
        Guardar.addActionListener(e -> guardarPelicula());
        Actualizar.addActionListener(e -> actualizarPelicula());
        Eliminar.addActionListener(e -> eliminarPelicula());
        Cartelera.addActionListener(e -> cargarPeliculasEnTabla());
    } 
        private void cargarComboPeliculas() {
        SeleccionarPelicula.removeAllItems();
        for (Pelicula p : peliculaData.ListarPeliculas()) {
            SeleccionarPelicula.addItem(p);
        }
    }
private void cargarPeliculasEnTabla() {
        modelo.setRowCount(0);
        for (Pelicula p : peliculaData.ListarPeliculas()) {
            if (!Cartelera.isSelected() || p.isEnCartelera()) {
                modelo.addRow(new Object[]{
                    p.getIdPelicula(),
                    p.getTitulo(),
                    p.getDirector(),
                    p.getActores(),
                    p.getOrigen(),
                    p.getGenero(),
                    p.getEstreno(),
                    p.isEnCartelera() ? "Sí" : "No"
                });
            }
        }
    }
private void buscarPelicula() {
        Pelicula seleccionada = (Pelicula) SeleccionarPelicula.getSelectedItem();
        if (seleccionada != null) {
            JOptionPane.showMessageDialog(this, "Seleccionaste: " + seleccionada.getTitulo());
        }
    }


    private void guardarPelicula() {
        
        Pelicula nueva = new Pelicula();
        nueva.setTitulo("Ejemplo");
        nueva.setDirector("Director");
        nueva.setActores("Actores");
        nueva.setOrigen("Origen");
        nueva.setGenero("Género");
        nueva.setEstreno(LocalDate.now());
        nueva.setEnCartelera(true);

        peliculaData.GuardarPelicula(nueva);
        cargarComboPeliculas();
        cargarPeliculasEnTabla();
    }

    private void actualizarPelicula() {
        Pelicula seleccionada = (Pelicula) SeleccionarPelicula.getSelectedItem();
        if (seleccionada != null) {
            seleccionada.setTitulo("Nuevo título");
            peliculaData.ActualizarPelicula(seleccionada);
            cargarPeliculasEnTabla();
        }
    }

    private void eliminarPelicula() {
        Pelicula seleccionada = (Pelicula) SeleccionarPelicula.getSelectedItem();
        if (seleccionada != null) {
            peliculaData.EliminarPelicula(seleccionada.getIdPelicula());
            cargarComboPeliculas();
            cargarPeliculasEnTabla();
        }
    }






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SeleccionarPelicula = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cartelera = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPelicula = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        Actualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        Eliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("Salir");

        Guardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Cartelera");

        SeleccionarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarPeliculaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Peliculas:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("En Cartelera");

        TablaPelicula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TablaPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Idpelicula", "Director", "Actores", "Origen", "Genero", "Estreno"
            }
        ));
        jScrollPane1.setViewportView(TablaPelicula);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cartelera)
                                    .addComponent(SeleccionarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Buscar)
                                .addGap(49, 49, 49)
                                .addComponent(Guardar)
                                .addGap(50, 50, 50)
                                .addComponent(Actualizar)
                                .addGap(52, 52, 52)
                                .addComponent(Eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(jButton4)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SeleccionarPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3))
                    .addComponent(Cartelera))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar)
                    .addComponent(Guardar)
                    .addComponent(Actualizar)
                    .addComponent(Eliminar)
                    .addComponent(jButton4))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionarPeliculaActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
         


        


    }//GEN-LAST:event_BuscarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_GuardarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        
        


    }//GEN-LAST:event_ActualizarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Buscar;
    private javax.swing.JRadioButton Cartelera;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private javax.swing.JComboBox SeleccionarPelicula;
    private javax.swing.JTable TablaPelicula;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables




}
