/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Asiento;
import Modelo.Comprador;
import Modelo.DetalleCompra;
import Modelo.Proyeccion;
import Persistencia.AsientoData;
import Persistencia.CompradorData;
import Persistencia.DetalleCompraData;
import Persistencia.PeliculaData;
import Persistencia.ProyeccionData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabri
 */
public class VistaDetalleCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaDetalleCompra
     */
    DefaultTableModel modelo = new DefaultTableModel();
    
    PeliculaData pd = new PeliculaData();
    ProyeccionData proyedata = new ProyeccionData();
    AsientoData ad = new AsientoData();
    CompradorData cd = new CompradorData();
    
    
    
    public VistaDetalleCompra() {
        initComponents();
        
        
        //cargar proyecciones
        ArrayList<Proyeccion> proyecciones = proyedata.listarProyecciones();
        DefaultComboBoxModel<Proyeccion> cbProye = new DefaultComboBoxModel<>();
        for (Proyeccion proyeccione : proyecciones) {
            cbProye.addElement(proyeccione);
        }
        Proyecciones.setModel(cbProye);
        
        //cargar compradores
        
        ArrayList<Comprador> compradores = cd.MostrarCompradores();
        DefaultComboBoxModel<Comprador> cbComprador = new DefaultComboBoxModel<>();
        for (Comprador compradore : compradores) {
            cbComprador.addElement(compradore);
        }
        Compradores.setModel(cbComprador);
        
        //cargar cantidad entradas
        Integer[] entradas = {1,2};
        DefaultComboBoxModel<Integer> cbentradas = new DefaultComboBoxModel<>();
        for (Integer entrada : entradas) {
            cbentradas.addElement(entrada);
        }
        Entradas.setModel(cbentradas);
        
        // cargar columnas 
        String[] columnas = {"Inicio","Proyeccion","Asiento","Asiento 2","Fecha Compra","Fecha Funcion","Comprador","Entradas","Descuento","Monto"};
        modelo.setColumnIdentifiers(columnas);
        tablaDetalle.setModel(modelo);
        
        Guardar.setEnabled(false);
        Asientos2.setEnabled(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FechaCompra = new com.toedter.calendar.JDateChooser();
        FechaFuncion = new com.toedter.calendar.JDateChooser();
        id = new javax.swing.JTextField();
        Proyecciones = new javax.swing.JComboBox<>();
        Asientos = new javax.swing.JComboBox<>();
        Compradores = new javax.swing.JComboBox<>();
        Monto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        Agregar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        BuscarPorId = new javax.swing.JButton();
        ListarTodo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Entradas = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Asientos2 = new javax.swing.JComboBox<>();
        lbPrecio = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lbComprador = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("id:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Proyeccion:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Asiento:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Fecha Compra:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Fecha Funcion:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Monto:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Comprador:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Cant. Entradas:");

        Proyecciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ProyeccionesItemStateChanged(evt);
            }
        });
        Proyecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProyeccionesActionPerformed(evt);
            }
        });

        Asientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsientosActionPerformed(evt);
            }
        });

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Inicio", "Proyeccion", "Asiento", "Asiento 2", "Fecha Compra", "Fecha Funcion", "Comprador", "Entradas", "Descuento", "Monto"
            }
        ));
        jScrollPane1.setViewportView(tablaDetalle);

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar por id");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        BuscarPorId.setText("Buscar por id");
        BuscarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorIdActionPerformed(evt);
            }
        });

        ListarTodo.setText("Listar todo");
        ListarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTodoActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar por dni");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel9.setText("Gestion Compra");

        Entradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradasActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Asiento 2:");

        Asientos2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Asientos2ItemStateChanged(evt);
            }
        });
        Asientos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Asientos2ActionPerformed(evt);
            }
        });

        lbPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdniKeyPressed(evt);
            }
        });

        jButton2.setText("Buscar comprador");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbComprador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(Agregar)
                .addGap(18, 18, 18)
                .addComponent(Guardar)
                .addGap(18, 18, 18)
                .addComponent(Actualizar)
                .addGap(18, 18, 18)
                .addComponent(Eliminar)
                .addGap(18, 18, 18)
                .addComponent(BuscarPorId)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(ListarTodo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaFuncion, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(FechaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Asientos2, javax.swing.GroupLayout.Alignment.LEADING, 0, 96, Short.MAX_VALUE)
                            .addComponent(Asientos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(41, 41, 41)
                                .addComponent(lbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Monto, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(Entradas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(260, 260, 260))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jButton2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Compradores, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(Proyecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(lbComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Compradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Entradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Proyecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(Asientos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(FechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FechaFuncion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar)
                    .addComponent(Guardar)
                    .addComponent(Actualizar)
                    .addComponent(Eliminar)
                    .addComponent(BuscarPorId)
                    .addComponent(ListarTodo)
                    .addComponent(jButton1))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        
        try {
            DetalleCompraData dcd = new DetalleCompraData();
            DetalleCompra detalleCompra = null;
            Proyeccion proyeccion = (Proyeccion) Proyecciones.getSelectedItem();
            Asiento asiento = (Asiento) Asientos.getSelectedItem();
            Asiento asiento2 = (Asiento) Asientos2.getSelectedItem();
            java.util.Date fcompra = FechaCompra.getDate();
            LocalDate fechaCompra = fcompra.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            java.util.Date fFuncion = FechaFuncion.getDate();
            LocalDate fechaFuncion = fFuncion.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            Comprador comprador = (Comprador) Compradores.getSelectedItem();
            Integer entradas =  (Integer) Entradas.getSelectedItem();
            
            
            double descuento ;
            double monto = proyeccion.getPrecio();
            switch (entradas) {
                case 1:
                    descuento = 0;
                    if (entradas == 1) {
                        detalleCompra = new DetalleCompra(proyeccion,asiento.getCodLugar(),fechaCompra,fechaFuncion,monto,comprador,entradas,descuento);
                        dcd.guardarDetalleCompra(detalleCompra);
                    }else if(entradas==2){
                        detalleCompra = new DetalleCompra(proyeccion,asiento.getCodLugar(),asiento2.getCodLugar(),fechaCompra,fechaFuncion,monto,comprador,entradas,descuento);
                        dcd.guardarDetalleCompra(detalleCompra);
                    }
                    
                    break;
                    case 2:
                    descuento = (monto*5)/100;
                    monto = monto-descuento;
                     if (entradas == 1) {
                        detalleCompra = new DetalleCompra(proyeccion,asiento.getCodLugar(),fechaCompra,fechaFuncion,monto,comprador,entradas,descuento);
                        dcd.guardarDetalleCompra(detalleCompra);
                    }else if(entradas==2){
                        detalleCompra = new DetalleCompra(proyeccion,asiento.getCodLugar(),asiento2.getCodLugar(),fechaCompra,fechaFuncion,monto,comprador,entradas,descuento);
                        dcd.guardarDetalleCompra(detalleCompra);
                    }
                    break;
                   
                default:
                    throw new AssertionError();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error, asegurese que los campos de numero sean numeros y no letras: " + e);
        }
        
        Guardar.setEnabled(false);
        Actualizar.setEnabled(true);
        Eliminar.setEnabled(true);
        Monto.setEnabled(true);
        id.setEnabled(true);
    }//GEN-LAST:event_GuardarActionPerformed

    private void ProyeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProyeccionesActionPerformed
        // TODO add your handling code here:
        Proyeccion proyeccion = (Proyeccion) Proyecciones.getSelectedItem();
        
        ArrayList<Asiento> asientos = ad.listarAsientos(proyeccion.getIdFuncion());
        DefaultComboBoxModel<Asiento> cbAsiento = new DefaultComboBoxModel<>();
        for (Asiento asiento : asientos) {
            cbAsiento.addElement(asiento);
        }
        Asientos.setModel(cbAsiento);
        
        
        
        
        
        ArrayList<Asiento> asiento = ad.listarAsientos(proyeccion.getIdFuncion());
        DefaultComboBoxModel<Asiento> cbAsientos = new DefaultComboBoxModel<>();
        for (Asiento asient : asiento) {
            cbAsientos.addElement(asient);
        }
        Asientos2.setModel(cbAsientos);
        
        
        
        
    }//GEN-LAST:event_ProyeccionesActionPerformed

    private void ListarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTodoActionPerformed
        // TODO add your handling code here:
        DetalleCompraData dcd = new DetalleCompraData();
        ArrayList<DetalleCompra> lista = dcd.listarTodasLasCompras();
        
        for (DetalleCompra detalleCompra : lista) {
            cargarDatos(detalleCompra);
        }
        
        
    }//GEN-LAST:event_ListarTodoActionPerformed

    private void BuscarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorIdActionPerformed
        // TODO add your handling code here:
        
        try {
            int iddetalle = Integer.parseInt(id.getText());
            DetalleCompraData dcd = new DetalleCompraData();
            DetalleCompra lista = dcd.buscarDetalleCompra(iddetalle);
            
            if (lista!=null) {
                cargarDatos(lista);
            }else if(lista==null){
                JOptionPane.showMessageDialog(null, "No se encontro ");
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error, asegurese que los campos de numero sean numeros y no letras: " + e);
        }
        
        
    }//GEN-LAST:event_BuscarPorIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            Comprador comprador = (Comprador) Compradores.getSelectedItem();
            
            DetalleCompraData dcd = new DetalleCompraData();
            
            ArrayList<DetalleCompra> lista = dcd.listarComprasPorComprador(comprador.getDni());
            for (DetalleCompra detalleCompra : lista) {
                cargarDatos(detalleCompra);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error, asegurese que los campos de numero sean numeros y no letras: " + e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        
        
        try {
            int iddetalle = Integer.parseInt(id.getText());
            DetalleCompraData dcd = new DetalleCompraData();
            
            dcd.eliminarDetalleCompra(iddetalle);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error, asegurese que los campos de numero sean numeros y no letras: " + e);
        }
        
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        
        try {
            DetalleCompraData dcd = new DetalleCompraData();
            DetalleCompra detalleCompra = null;
            int idDetalle = Integer.parseInt(id.getText());
            Proyeccion proyeccion = (Proyeccion) Proyecciones.getSelectedItem();
            Asiento asiento = (Asiento) Asientos.getSelectedItem();
            Asiento asiento2 = (Asiento) Asientos2.getSelectedItem();
            java.util.Date fcompra = FechaCompra.getDate();
            LocalDate fechaCompra = fcompra.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            java.util.Date fFuncion = FechaFuncion.getDate();
            LocalDate fechaFuncion = fFuncion.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            Comprador comprador = (Comprador) Compradores.getSelectedItem();
            Integer entradas = (Integer) Entradas.getSelectedItem();
            double descuento ;
            double monto = Double.parseDouble(Monto.getText());
            switch (entradas) {
                case 1:
                    descuento = 0;
                    detalleCompra = new DetalleCompra(idDetalle,proyeccion,asiento.getCodLugar(),asiento2.getCodLugar(),fechaCompra,fechaFuncion,monto,comprador,entradas,descuento);
                    dcd.modificarDetalleCompra(detalleCompra);
                    break;
                    case 2:
                    descuento = (monto*20)/100;
                    monto = monto-descuento;
                    detalleCompra = new DetalleCompra(idDetalle,proyeccion,asiento.getCodLugar(),asiento2.getCodLugar(),fechaCompra,fechaFuncion,monto,comprador,entradas,descuento);
                    dcd.modificarDetalleCompra(detalleCompra);
                    break;
                    
                default:
                    throw new AssertionError();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error, asegurese que los campos de numero sean numeros y no letras: " + e);
        }
        
        
    }//GEN-LAST:event_ActualizarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        
        Guardar.setEnabled(true);
        Actualizar.setEnabled(false);
        Eliminar.setEnabled(false);
        Monto.setEnabled(false);
        id.setEnabled(false);
        
        
    }//GEN-LAST:event_AgregarActionPerformed

    private void EntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradasActionPerformed
        // TODO add your handling code here:
        
        try {
            //habilitar/desabilitar asiento2
            Integer entradas = (Integer) Entradas.getSelectedItem();
        if (entradas == 2) {
            Asientos2.setEnabled(true);
        }else if (entradas == 1) {
            Asientos2.setEnabled(false);
        }
        
        //mostrar precio
        Proyeccion pro = (Proyeccion) Proyecciones.getSelectedItem();
        int entrada = (int) Entradas.getSelectedItem();
        
        if (entrada==1) {
            lbPrecio.setText(pro.getPrecio()+"$");
        }else if(entrada==2){
            double descuento = (pro.getPrecio()*5)/100;
            double precio = pro.getPrecio()-descuento;
            lbPrecio.setText(precio+"$");
        }
        
        } catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(null, "Error, asegurese que los campos de numero sean numeros y no letras: " + e);
        }
        
        
        
        
        
    }//GEN-LAST:event_EntradasActionPerformed

    private void ProyeccionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ProyeccionesItemStateChanged
        //               TODO add your handling code here:
        
        
        
        
        
    }//GEN-LAST:event_ProyeccionesItemStateChanged

    private void txtdniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyPressed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtdniKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
            try {
        CompradorData cd = new CompradorData();
        int dni = Integer.parseInt(txtdni.getText());
        
        // 1. Buscas el comprador en la BD
        Comprador compradorEncontrado = cd.BuscarComprador(dni);
        
        if (compradorEncontrado != null) {
            // 2. Actualizas el Label (esto estaba bien)
            lbComprador.setText(compradorEncontrado.getNombre() + " - " + compradorEncontrado.getDni());
            
            // 3. --- LA MAGIA PARA EL COMBOBOX ---
            // Recorremos el combo para encontrar el objeto que COINCIDA en DNI
            for (int i = 0; i < Compradores.getItemCount(); i++) {
                Comprador c = (Comprador) Compradores.getItemAt(i);
                
                if (c.getDni() == compradorEncontrado.getDni()) {
                    Compradores.setSelectedIndex(i); // ¡Lo seleccionamos por índice!
                    break; // Ya lo encontramos, dejamos de buscar
                }
            }
            // ------------------------------------
            
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ningún comprador con DNI: " + dni);
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, ingrese un DNI válido (solo números).");
    }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Asientos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Asientos2ActionPerformed
        // TODO add your handling code here:
             // 1. Obtenemos los objetos (con validación de null por seguridad)
    Asiento asiento1 = (Asiento) Asientos.getSelectedItem();
    Asiento asiento2 = (Asiento) Asientos2.getSelectedItem();

    // Si alguno es null (aún no se cargaron), no hacemos nada
    if (asiento1 == null || asiento2 == null) {
        return;
    }

    // 2. Comparación por ID (codLugar) - ¡Es infalible!
    if (asiento1.getCodLugar() == asiento2.getCodLugar()) {
        
        // CASO: SON IGUALES (Error)
        Guardar.setEnabled(false); // Desactivamos el botón
        JOptionPane.showMessageDialog(null, "Error: No puede seleccionar el mismo asiento dos veces.");
        
    } else {
        
        // CASO: SON DISTINTOS (Correcto)
        // ¡IMPORTANTE! Debes volver a activar el botón si el usuario corrige el error
        Guardar.setEnabled(true); 
    }
        
        
        
    }//GEN-LAST:event_Asientos2ActionPerformed

    private void Asientos2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Asientos2ItemStateChanged
        // TODO add your handling code here:
   
        
        
        
        
    }//GEN-LAST:event_Asientos2ItemStateChanged

    private void AsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsientosActionPerformed
        // TODO add your handling code here:
        
             // 1. Obtenemos los objetos (con validación de null por seguridad)
    Asiento asiento1 = (Asiento) Asientos.getSelectedItem();
    Asiento asiento2 = (Asiento) Asientos2.getSelectedItem();

    // Si alguno es null (aún no se cargaron), no hacemos nada
    if (asiento1 == null || asiento2 == null) {
        return;
    }

    // 2. Comparación por ID (codLugar) - ¡Es infalible!
    if (asiento1.getCodLugar() == asiento2.getCodLugar()) {
        
        // CASO: SON IGUALES (Error)
        Guardar.setEnabled(false); // Desactivamos el botón
        JOptionPane.showMessageDialog(null, "Error: No puede seleccionar el mismo asiento dos veces.");
        
    } else {
        
        // CASO: SON DISTINTOS (Correcto)
        // ¡IMPORTANTE! Debes volver a activar el botón si el usuario corrige el error
        Guardar.setEnabled(true); 
    }
    }//GEN-LAST:event_AsientosActionPerformed
    public void cargarDatos(DetalleCompra dc){
        AsientoData ad = new AsientoData();
        Asiento asiento1 = ad.buscarAsientoPorcodLugar(dc.getCodLugar());
        Asiento asiento2 = ad.buscarAsientoPorcodLugar(dc.getCodLugar2());
        modelo.addRow(new Object[]{dc.getProyeccion().getHorInicio(),dc.getProyeccion().getPelicula(),asiento1,asiento2,dc.getFechaCompra(),dc.getFechaFuncion(),dc.getComprador().getNombre(),dc.getCantidadtickets(),dc.getDescuento(),dc.getMonto()});
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Agregar;
    private javax.swing.JComboBox<Asiento> Asientos;
    private javax.swing.JComboBox<Asiento> Asientos2;
    private javax.swing.JButton BuscarPorId;
    private javax.swing.JComboBox<Comprador> Compradores;
    private javax.swing.JButton Eliminar;
    private javax.swing.JComboBox<Integer> Entradas;
    private com.toedter.calendar.JDateChooser FechaCompra;
    private com.toedter.calendar.JDateChooser FechaFuncion;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton ListarTodo;
    private javax.swing.JTextField Monto;
    private javax.swing.JComboBox<Proyeccion> Proyecciones;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbComprador;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTextField txtdni;
    // End of variables declaration//GEN-END:variables
}
