/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Asiento;
import Modelo.DetalleTicket;
import Modelo.Proyeccion;
import Persistencia.AsientoData;
import Persistencia.DetalleTicketData;
import Persistencia.ProyeccionData;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabri
 */
public class VistaDetalleTicket extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaDetalleTicket
     */
    
    DefaultTableModel modelo1 = new DefaultTableModel();
    DefaultTableModel modelo2 = new DefaultTableModel();
    DefaultTableModel modelo3 = new DefaultTableModel();
    
    
    AsientoData ad = new AsientoData();
    ProyeccionData pd = new ProyeccionData();
    public VistaDetalleTicket() {
        initComponents();
        
        // mostrar proyecciones
        ArrayList<Proyeccion> proyecciones = pd.listarProyecciones();
        
        DefaultComboBoxModel<Proyeccion> comboBoxProyeccion = new DefaultComboBoxModel();
        for (Proyeccion proyeccione : proyecciones) {
            comboBoxProyeccion.addElement(proyeccione);
        }
        Proyecciones.setModel(comboBoxProyeccion);
        
        
        // poner las columnas a la tabla
        String[] columnas = {"ID","Funcion","Asiento","Precio"};
        modelo2.setColumnIdentifiers(columnas);
        tablaDetalle.setModel(modelo2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Proyecciones = new javax.swing.JComboBox<>();
        Asientos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Precio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        idDetalle = new javax.swing.JSpinner();
        Guardar = new javax.swing.JButton();
        ListarPorFuncion = new javax.swing.JButton();
        BuscarPorId = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setText("Detalle de Ticket");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Funciones:");

        Proyecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProyeccionesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Precio:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Asientos disponibles:");

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Funcion", "Asiento", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaDetalle);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("id Detalle ticket:");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        ListarPorFuncion.setText("Listar por Funcion");
        ListarPorFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarPorFuncionActionPerformed(evt);
            }
        });

        BuscarPorId.setText("Buscar por id");
        BuscarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(Guardar)
                        .addGap(90, 90, 90)
                        .addComponent(ListarPorFuncion)
                        .addGap(73, 73, 73)
                        .addComponent(BuscarPorId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(idDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Proyecciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Asientos, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(idDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Proyecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3))
                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardar)
                    .addComponent(ListarPorFuncion)
                    .addComponent(BuscarPorId))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProyeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProyeccionesActionPerformed
        // TODO add your handling code here:
        AsientoData ad = new AsientoData();
        Proyeccion proyeccion = (Proyeccion) Proyecciones.getSelectedItem();
        int id = proyeccion.getIdFuncion();
        ArrayList<Asiento> asientos = ad.listarAsientos(id);
        DefaultComboBoxModel<Asiento> comboboxAsiento = new DefaultComboBoxModel<>();
        for (Asiento asiento : asientos) {
            comboboxAsiento.addElement(asiento);
        }
        Asientos.setModel(comboboxAsiento);
    }//GEN-LAST:event_ProyeccionesActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        try {
            Proyeccion proyeccion = (Proyeccion) Proyecciones.getSelectedItem();
        Asiento asiento = (Asiento) Asientos.getSelectedItem();
        int lugarAsiento = asiento.getCodLugar();
        
        int precio = Integer.parseInt(Precio.getText());
        
        DetalleTicket detalle = new DetalleTicket(proyeccion,lugarAsiento,precio);
        
        DetalleTicketData dtd = new DetalleTicketData();
        dtd.guardarDetalle(detalle);
        } catch (NumberFormatException  e) {
            JOptionPane.showMessageDialog(null, "El precio debe ser un numero");
        }
        
        
        
    }//GEN-LAST:event_GuardarActionPerformed

    private void ListarPorFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarPorFuncionActionPerformed
        // TODO add your handling code here:
        
        Proyeccion proyeccion = (Proyeccion) Proyecciones.getSelectedItem();
        int idFuncion = proyeccion.getIdFuncion();
        
        DetalleTicketData dtd = new DetalleTicketData();
        
        ArrayList<DetalleTicket> detalles = dtd.listarDetallesPorFuncion(idFuncion);
        
        for (DetalleTicket detalle : detalles) {
            cargarDatos(detalle);
        }
    }//GEN-LAST:event_ListarPorFuncionActionPerformed

    private void BuscarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorIdActionPerformed
        // TODO add your handling code here:
        
        int id = (int) idDetalle.getValue();
        DetalleTicketData dtd = new DetalleTicketData();
        DetalleTicket dt = dtd.buscarDetallePorTicket(id);
        
        cargarDatos(dt);
        
        
    }//GEN-LAST:event_BuscarPorIdActionPerformed
    public void cargarDatos(DetalleTicket d){
    
        modelo2.addRow(new Object[]{d.getCodD(),d.getProyeccion(),d.getCodLugar(),d.getSubTotal()});
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Asiento> Asientos;
    private javax.swing.JButton BuscarPorId;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton ListarPorFuncion;
    private javax.swing.JTextField Precio;
    private javax.swing.JComboBox<Proyeccion> Proyecciones;
    private javax.swing.JSpinner idDetalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDetalle;
    // End of variables declaration//GEN-END:variables
}
