/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Comprador;
import Modelo.TicketCompra;
import Persistencia.CompradorData;
import Persistencia.DetalleTicketData;
import Persistencia.ProyeccionData;
import Persistencia.TicketCompraData;
import java.util.ArrayList;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabri
 */
public class VistaTicketCompra extends javax.swing.JInternalFrame {
DefaultTableModel modelo;
TicketCompraData ticketData = new TicketCompraData();

    /**
     * Creates new form VistaTicketCompra
     */
    public VistaTicketCompra() {
        initComponents();
        modelo = new DefaultTableModel();

        String[] tabla = { "idTicketCompra", "codD", "fechacompra", "fechafuncion","monto", "comprador", "cantidadtickets", "descuento"};
        modelo.setColumnIdentifiers(tabla);
        jTablacompra.setModel(modelo);
        
        
        Guardar.setEnabled(false);
    }
    public void cargarTabla() {
    DefaultTableModel modelo = (DefaultTableModel) jTablacompra.getModel();
    modelo.setRowCount(0); // limpia tabla
    ArrayList<TicketCompra> lista = ticketData.MostrarTicketComprados(Integer.parseInt(dniComprador.getText()));
    for (TicketCompra t : lista) {
        modelo.addRow(new Object[]{
            t.getIdTicketCompra(),
            t.getcodD(),
            t.getFechaCompra(),
            t.getFechaFuncion(),
            t.getCantidadtickets(),
            t.getDescuento(),
            t.getMonto(),
            t.getComprador().getDni()
        });
    }
    if (lista.isEmpty()) {
        JOptionPane.showMessageDialog(null, "No quedan tickets para el DNI ingresado.");
    } else {
        JOptionPane.showMessageDialog(null, "Tickets que quedan:");
    }




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idTicketCompra = new javax.swing.JTextField();
        dniComprador = new javax.swing.JTextField();
        Monto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        FechaCompra = new com.toedter.calendar.JDateChooser();
        FechaFuncion = new com.toedter.calendar.JDateChooser();
        Agregar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        ListarTickets = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablacompra = new javax.swing.JTable();
        Guardar = new javax.swing.JButton();
        jEliminar = new javax.swing.JButton();
        codD = new javax.swing.JTextField();
        Entradas = new javax.swing.JSpinner();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("IdTicket:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Fecha Compra:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Fecha Funcion:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Monto:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("DNI Comprador:");

        dniComprador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniCompradorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel6.setText("Ticket Compra");

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar por id");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        ListarTickets.setText("Listar Tickets por dni");
        ListarTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTicketsActionPerformed(evt);
            }
        });

        jTablacompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IdTicket", "codD", "Fecha Compra", "Fecha Funcion", "Monto", "Comprador", "Cant. tickets", "descuento"
            }
        ));
        jScrollPane1.setViewportView(jTablacompra);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jEliminar.setText("Eliminar Ticket");
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("codDetalle:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Entradas:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Descuento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 115, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(259, 259, 259))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel7))
                                            .addGap(48, 48, 48)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(idTicketCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(codD, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(FechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addGap(260, 260, 260))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Entradas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dniComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FechaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap()))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Agregar)
                .addGap(18, 18, 18)
                .addComponent(Guardar)
                .addGap(17, 17, 17)
                .addComponent(Buscar)
                .addGap(18, 18, 18)
                .addComponent(jEliminar)
                .addGap(18, 18, 18)
                .addComponent(ListarTickets)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTicketCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(FechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(FechaFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniComprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar)
                    .addComponent(Buscar)
                    .addComponent(ListarTickets)
                    .addComponent(Guardar)
                    .addComponent(jEliminar))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        try {
    int id = Integer.parseInt(idTicketCompra.getText());
    TicketCompra ticket = ticketData.BuscarTicketCompra(id);

    if (ticket != null) {
        // Cargar campos individuales
        FechaCompra.setDate(Date.valueOf(ticket.getFechaCompra()));
         FechaFuncion.setDate(Date.valueOf(ticket.getFechaFuncion()));
        Monto.setText(String.valueOf(ticket.getMonto()));
        dniComprador.setText(String.valueOf(ticket.getComprador().getDni()));

        // Cargar tabla
        DefaultTableModel modelo = (DefaultTableModel) jTablacompra.getModel();
        modelo.setRowCount(0); // limpia tabla

        modelo.addRow(new Object[]{
            ticket.getIdTicketCompra(),
            ticket.getcodD(),
            ticket.getFechaCompra(),
            ticket.getFechaFuncion(),
            ticket.getCantidadtickets(),
            ticket.getDescuento(),
            ticket.getMonto(),
            ticket.getComprador().getDni()

        });
    } else {
        JOptionPane.showMessageDialog(null, "No se encontró el ticket.");
    }
} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Error al buscar: " + ex.getMessage());
}

    }//GEN-LAST:event_BuscarActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        // TODO add your handling code here:
        try {
    String idTexto = idTicketCompra.getText().trim();

    if (idTexto.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingresá el ID del ticket a eliminar.");
        return;
    }

    int id = Integer.parseInt(idTexto);

    // Confirmación opcional
    int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que querés eliminar el ticket?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
    if (confirmacion != JOptionPane.YES_OPTION) {
        return;
    }

    TicketCompraData ticketData = new TicketCompraData();
    ticketData.EliminarTicketCompra(id);

    // Refrescar tabla
    cargarTabla();

} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, "El ID debe ser un número válido.");
} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Error al eliminar ticket: " + ex.getMessage());
}

    }//GEN-LAST:event_jEliminarActionPerformed

    private void ListarTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTicketsActionPerformed
        // TODO add your handling code here:
        try {
    String dniTexto = dniComprador.getText().trim();

    if (dniTexto.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, ingresá un DNI.");
        return;
    }

    int dni = Integer.parseInt(dniTexto);
    TicketCompraData ticketData = new TicketCompraData();
    ArrayList<TicketCompra> lista = ticketData.MostrarTicketComprados(dni);

    DefaultTableModel modelo = (DefaultTableModel) jTablacompra.getModel();
    modelo.setRowCount(0); // limpia tabla

    if (lista.isEmpty()) {
        JOptionPane.showMessageDialog(null, "No se encontraron tickets para el DNI ingresado.");
    } else {
        for (TicketCompra t : lista) {
            modelo.addRow(new Object[]{
                t.getIdTicketCompra(),
                t.getcodD(),
                t.getFechaCompra(),
                t.getFechaFuncion(),
                t.getMonto(),
                t.getComprador().getDni(),
                t.getCantidadtickets(),
                t.getDescuento()
                
                
            });
        }
    }

} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, "El DNI debe ser un número válido.");
} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Error al listar tickets: " + ex.getMessage());
}

    }//GEN-LAST:event_ListarTicketsActionPerformed

    private void dniCompradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniCompradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniCompradorActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        Guardar.setEnabled(true);
        idTicketCompra.setEnabled(false);
        Monto.setEnabled(false);
        Entradas.setEnabled(false);
        jTextField2.setEnabled(false);
        
    }//GEN-LAST:event_AgregarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        CompradorData cd = new CompradorData();
        DetalleTicketData dtd = new DetalleTicketData();
        TicketCompraData tcd = new TicketCompraData();
        try {
            TicketCompra ticketCompra = null;
            int coD = Integer.parseInt(codD.getText());
            java.util.Date fechaCompra = FechaCompra.getDate();
            LocalDate ldFechaCompra = fechaCompra.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            java.util.Date fechaFuncion = FechaFuncion.getDate();
            LocalDate ldFechaFuncion = fechaFuncion.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            
            
            
            int dni = Integer.parseInt(dniComprador.getText());
            Comprador comprado = cd.BuscarComprador(dni);
            int entradas  = cd.BuscarComprador(dni).getMaxticketpermitidos();
            
            double proyPrecio = dtd.buscarDetallePorTicket(coD).getProyeccion().getPrecio();
            
            switch (entradas) {
                case 1:
                    double monto = proyPrecio;
                    ticketCompra = new TicketCompra(coD,ldFechaCompra,ldFechaFuncion,monto,comprado,entradas,0);
                    tcd.GuardarTicketCompra(ticketCompra);
                    break;
                    
                case 2:
                    double descuento =  (proyPrecio*5)/100;
                    monto = proyPrecio-descuento;
                    ticketCompra = new TicketCompra(coD,ldFechaCompra,ldFechaFuncion,monto,comprado,entradas,descuento);
                    tcd.GuardarTicketCompra(ticketCompra);
                    break;
                case 3:
                    descuento =  (proyPrecio*10)/100;
                    monto = proyPrecio-descuento;
                    ticketCompra = new TicketCompra(coD,ldFechaCompra,ldFechaFuncion,monto,comprado,entradas,descuento);
                    tcd.GuardarTicketCompra(ticketCompra);
                    break;
                case 4:
                    descuento =  (proyPrecio*15)/100;
                    monto = proyPrecio-descuento;
                    ticketCompra = new TicketCompra(coD,ldFechaCompra,ldFechaFuncion,monto,comprado,entradas,descuento);
                    tcd.GuardarTicketCompra(ticketCompra);
                    break;
                case 5:
                    descuento =  (proyPrecio*20)/100;
                    monto = proyPrecio-descuento;
                    ticketCompra = new TicketCompra(coD,ldFechaCompra,ldFechaFuncion,monto,comprado,entradas,descuento);
                    tcd.GuardarTicketCompra(ticketCompra);
                    break;
                  
                default:
                    throw new AssertionError();
            }
            
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error, asegurese que los compaos de numeros se agreguen numeros y no letras."+ e);
        }
        
        idTicketCompra.setEnabled(true);
        Monto.setEnabled(true);
        Entradas.setEnabled(true);
        jTextField2.setEnabled(true);
        
        
    }//GEN-LAST:event_GuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Buscar;
    private javax.swing.JSpinner Entradas;
    private com.toedter.calendar.JDateChooser FechaCompra;
    private com.toedter.calendar.JDateChooser FechaFuncion;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton ListarTickets;
    private javax.swing.JTextField Monto;
    private javax.swing.JTextField codD;
    private javax.swing.JTextField dniComprador;
    private javax.swing.JTextField idTicketCompra;
    private javax.swing.JButton jEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablacompra;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
