/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Comprador;
import Persistencia.CompradorData;
import java.time.LocalDate;
import java.time.ZoneId;
import static java.time.temporal.TemporalQueries.zone;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabri
 */
public class VistaComprador extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaComprador
     */
    DefaultTableModel modelo;
    DefaultTableModel modelo2;
    public VistaComprador() {
        initComponents();
        Entradas.setModel(new SpinnerNumberModel(1, 1, 5, 1));

        //lenando comboBox
        modelo = new DefaultTableModel();
        
        String[] pagos = {"Efectivo","Debito","Transferencia"};
        
        DefaultComboBoxModel<String> comboPago = new DefaultComboBoxModel();
        for (String pago : pagos) {
            comboPago.addElement(pago);
        }
        MedioPago.setModel(comboPago);
        
        //llenando tabla
        modelo2 = new DefaultTableModel();
        String[] columnas = {"DNI","Nombre","Nacimiento","Contraseña","Medio Pago","Cantidad Entradas"};
        modelo2.setColumnIdentifiers(columnas);
        tablaCompradores.setModel(modelo2);
        
        
        Guardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        Nacimiento = new com.toedter.calendar.JDateChooser();
        Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Contraseña = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompradores = new javax.swing.JTable();
        Guardar = new javax.swing.JButton();
        Actualizar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        BuscarPorDni = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Entradas = new javax.swing.JSpinner();
        MedioPago = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("DNI:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Fecha Nacimiento:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Contraseña:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Medio de Pago:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Cantidad de Entradas:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setText("Datos Comprador");

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        tablaCompradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Nacimiento", "Contraseña", "Medio de Pago", "Cantidad Entradas"
            }
        ));
        tablaCompradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCompradoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCompradores);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        BuscarPorDni.setText("Buscar comprador por DNI");
        BuscarPorDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorDniActionPerformed(evt);
            }
        });

        jButton1.setText("Listar todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(Nacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre)
                            .addComponent(dni))))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel4)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(Entradas))
                    .addComponent(MedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Guardar)
                .addGap(68, 68, 68)
                .addComponent(Actualizar)
                .addGap(74, 74, 74)
                .addComponent(Borrar)
                .addGap(71, 71, 71)
                .addComponent(BuscarPorDni)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(MedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(Entradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar)
                    .addComponent(Guardar)
                    .addComponent(Actualizar)
                    .addComponent(Borrar)
                    .addComponent(BuscarPorDni))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        
        
        Guardar.setEnabled(true);
        Actualizar.setEnabled(false);
        Borrar.setEnabled(false);
        BuscarPorDni.setEnabled(false);
    }//GEN-LAST:event_AgregarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        
        
        try {
            int DNI = Integer.parseInt(dni.getText());
            String nombre = Nombre.getText();
            java.util.Date fc = Nacimiento.getDate();
            LocalDate nacimiento = fc.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            char[] contraseña = Contraseña.getPassword();
            String contra = new String(contraseña);
            String medioPago = (String) MedioPago.getSelectedItem();
            
            int entradas = (int) Entradas.getValue();
            while(entradas>5 || entradas<1){
                Guardar.setEnabled(false);
            }
            Comprador comprador = new Comprador(DNI,nombre,nacimiento,contra,medioPago,entradas);
            CompradorData cd = new CompradorData();
            cd.AgregarComprador(comprador);
            
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Verifique el campos numérico DNI.");
    }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_GuardarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        try {
        int DNI = Integer.parseInt(dni.getText());
            String nombre = Nombre.getText();
            java.util.Date fc = Nacimiento.getDate();
            LocalDate nacimiento = fc.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            char[] contraseña = Contraseña.getPassword();
            String contra = new String(contraseña);
            String medioPago = (String) MedioPago.getSelectedItem();
            int entradas = (int) Entradas.getValue();
            
            Comprador comprador = new Comprador(DNI,nombre,nacimiento,contra,medioPago,entradas);
            CompradorData cd = new CompradorData();
            cd.ActualizarComprador(comprador);
            
            } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Verifique el campos numérico DNI.");
    }
        
    }//GEN-LAST:event_ActualizarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
        
        try{
            int DNI = Integer.parseInt(dni.getText());
            CompradorData cd = new CompradorData();
            cd.EliminarComprador(DNI);
            
            
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Verifique el campos numérico DNI.");
    }
        
        
    }//GEN-LAST:event_BorrarActionPerformed

    private void BuscarPorDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorDniActionPerformed
        // TODO add your handling code here:
        
                try{
            int DNI = Integer.parseInt(dni.getText());
            CompradorData cd = new CompradorData();
            Comprador comprador = cd.BuscarComprador(DNI);
            
            cargarDatos(comprador);
            
            
            
            
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Verifique el campos numérico DNI.");
    }
        
        
    }//GEN-LAST:event_BuscarPorDniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        CompradorData cd = new CompradorData();
        for (Comprador MostrarCompradore : cd.MostrarCompradores()) {
            cargarDatos(MostrarCompradore);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaCompradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCompradoresMouseClicked
        // TODO add your handling code here:
        
        int fila = tablaCompradores.getSelectedRow();
        
        if (fila>=0) {
            
            int DNI = (int) tablaCompradores.getValueAt(fila, 0);
            String nombre = (String) tablaCompradores.getValueAt(fila, 1);
            LocalDate nacimiento = (LocalDate) tablaCompradores.getValueAt(fila, 2);
            String pago = (String) tablaCompradores.getValueAt(fila, 3);
            int entradas = (int) tablaCompradores.getValueAt(fila, 5);
            
            dni.setText(DNI+ "");
            Nombre.setText(nombre);
            Nacimiento.setDate(Date.from(nacimiento.atStartOfDay(ZoneId.systemDefault()).toInstant()));
            MedioPago.setSelectedItem(pago);
            Entradas.setValue(entradas);
            
            
        }
    }//GEN-LAST:event_tablaCompradoresMouseClicked

    public void cargarDatos(Comprador comprador){
    
        modelo2.addRow(new Object[]{comprador.getDni(),comprador.getNombre(),comprador.getFechaNac(),comprador.getPassword(),comprador.getMedioDePago(),comprador.getMaxticketpermitidos()});
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton BuscarPorDni;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JSpinner Entradas;
    private javax.swing.JButton Guardar;
    private javax.swing.JComboBox<String> MedioPago;
    private com.toedter.calendar.JDateChooser Nacimiento;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField dni;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCompradores;
    // End of variables declaration//GEN-END:variables
}
