/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;
import Modelo.Pelicula;
import Persistencia.PeliculaData;
import java.awt.Graphics;
import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import static java.time.temporal.TemporalQueries.zone;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author chich
 */
public class VistaPeliculas extends javax.swing.JInternalFrame {
 DefaultTableModel modelo = new DefaultTableModel();
 private PeliculaData  peliculaData;   
    /**
     * Creates new form Peliculas
     */
    public VistaPeliculas() {
        
        initComponents();
        
        
        String[] tabla = { "idPelicula", "Titulo", "director", "actores", "origen", "genero","estreno", "encartelera"};
        modelo.setColumnIdentifiers(tabla);
        TablaPelicula.setModel(modelo);
        
        
        Guardar.setEnabled(false);
        
        /*
        peliculaData = new PeliculaData();
        modelo = (DefaultTableModel) TablaPelicula.getModel();
        cargarComboPeliculas();
        cargarPeliculasEnTabla();
        
        Buscar.addActionListener(e -> buscarPelicula());
        Guardar.addActionListener(e -> guardarPelicula());
        Actualizar.addActionListener(e -> actualizarPelicula());
        Eliminar.addActionListener(e -> eliminarPelicula());
        Cartelera.addActionListener(e -> cargarPeliculasEnTabla());
    
    
        */
    } 
    /*
        private void cargarComboPeliculas() {
        SeleccionarPelicula.removeAllItems();
        for (Pelicula p : peliculaData.ListarPeliculas()) {
            SeleccionarPelicula.addItem(p);
        }
    }
        
private void cargarPeliculasEnTabla() {
        modelo.setRowCount(0);
        for (Pelicula p : peliculaData.ListarPeliculas()) {
            if (!Cartelera.isSelected() || p.isEnCartelera()) {
                modelo.addRow(new Object[]{
                    p.getIdPelicula(),
                    p.getTitulo(),
                    p.getDirector(),
                    p.getActores(),
                    p.getOrigen(),
                    p.getGenero(),
                    p.getEstreno(),
                    p.isEnCartelera() ? "Sí" : "No"
                });
            }
        }
    }
private void buscarPelicula() {
        Pelicula seleccionada = (Pelicula) SeleccionarPelicula.getSelectedItem();
        if (seleccionada != null) {
            JOptionPane.showMessageDialog(this, "Seleccionaste: " + seleccionada.getTitulo());
        }
    }


  

    private void actualizarPelicula() {
        Pelicula seleccionada = (Pelicula) SeleccionarPelicula.getSelectedItem();
        if (seleccionada != null) {
            seleccionada.setTitulo("Nuevo título");
            peliculaData.ActualizarPelicula(seleccionada);
            cargarPeliculasEnTabla();
        }
    }

    private void eliminarPelicula() {
        Pelicula seleccionada = (Pelicula) SeleccionarPelicula.getSelectedItem();
        if (seleccionada != null) {
            peliculaData.EliminarPelicula(seleccionada.getIdPelicula());
            cargarComboPeliculas();
            cargarPeliculasEnTabla();
        }
    }



*/


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Actualizar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cartelera = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPelicula = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Origen = new javax.swing.JTextField();
        Genero = new javax.swing.JTextField();
        idPelicula = new javax.swing.JTextField();
        Titulo = new javax.swing.JTextField();
        Director = new javax.swing.JTextField();
        Actores = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Estreno = new com.toedter.calendar.JDateChooser();
        listarPeliculas = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        Actualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        Eliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Guardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setText("Pelicula");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("En Cartelera:");

        Cartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarteleraActionPerformed(evt);
            }
        });

        TablaPelicula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TablaPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Idpelicula", "Titulo", "Director", "Actores", "Origen", "Genero", "Estreno", "Cartelera"
            }
        ));
        jScrollPane1.setViewportView(TablaPelicula);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("idPelicula:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Titulo:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Director:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Actores:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Origen:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Genero:");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Estreno:");

        idPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPeliculaActionPerformed(evt);
            }
        });

        Actores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActoresActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listarPeliculas.setText("Listar Peliculas");
        listarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPeliculasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(342, 342, 342))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(listarPeliculas)
                        .addGap(50, 50, 50))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(29, 29, 29)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(29, 29, 29)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idPelicula)
                            .addComponent(Titulo)
                            .addComponent(Director)
                            .addComponent(Actores, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(Estreno, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Genero))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cartelera)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(Origen))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(160, 160, 160)
                        .addComponent(Guardar)
                        .addGap(45, 45, 45)
                        .addComponent(Actualizar)
                        .addGap(47, 47, 47)
                        .addComponent(Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Buscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(idPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Director, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cartelera)
                                    .addComponent(Actores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Origen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(Estreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listarPeliculas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar)
                    .addComponent(Guardar)
                    .addComponent(Actualizar)
                    .addComponent(Eliminar)
                    .addComponent(jButton1))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
         
        try {
            int id = Integer.parseInt(idPelicula.getText());
            PeliculaData pd = new PeliculaData();
            Pelicula peli = pd.BuscarPelicula(id);
            cargarDatos(peli);
            
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El id debe ser un numero");
        }
        

        


    }//GEN-LAST:event_BuscarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        
        
        String titulo = Titulo.getText();
        String director = Director.getText();
        String actore = Actores.getText();
        String origen = Origen.getText();
        String genero = Genero.getText();
        java.util.Date estrenoDate = Estreno.getDate();
        LocalDate estreno = estrenoDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        boolean cartelera = Cartelera.isSelected();
        
        Pelicula pelicula = new Pelicula(titulo,director,actore,origen,genero,estreno,cartelera);
        PeliculaData pd = new PeliculaData();
        pd.GuardarPelicula(pelicula);
        
        
        
        
        
        
        
        Actualizar.setEnabled(true);
        Eliminar.setEnabled(true);
        Buscar.setEnabled(true);
        Guardar.setEnabled(false);
       
    }//GEN-LAST:event_GuardarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        
        String titulo = Titulo.getText();
        String director = Director.getText();
        String actore = Actores.getText();
        String origen = Origen.getText();
        String genero = Genero.getText();
        java.util.Date estrenoDate = Estreno.getDate();
        LocalDate estreno = estrenoDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        boolean cartelera = Cartelera.isSelected();
        
        Pelicula pelicula = new Pelicula(titulo,director,actore,origen,genero,estreno,cartelera);
        PeliculaData pd = new PeliculaData();
        pd.ActualizarPelicula(pelicula);


    }//GEN-LAST:event_ActualizarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        
        try {
            int id = Integer.parseInt(idPelicula.getText());
            PeliculaData pd = new PeliculaData();
            pd.EliminarPelicula(id);
            
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El id debe ser un numero");
        }
        
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void CarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarteleraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarteleraActionPerformed

    private void idPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPeliculaActionPerformed

    private void ActoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActoresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Actualizar.setEnabled(false);
        Eliminar.setEnabled(false);
        Buscar.setEnabled(false);
        Guardar.setEnabled(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPeliculasActionPerformed
        // TODO add your handling code here:
        PeliculaData pd = new PeliculaData();
        
        for (Pelicula ListarPelicula : pd.ListarPeliculas()) {
            cargarDatos(ListarPelicula);
        }
        
        
        
    }//GEN-LAST:event_listarPeliculasActionPerformed

    
    public void cargarDatos(Pelicula p){
    
        modelo.addRow(new Object[]{p.getIdPelicula(),p.getTitulo(),p.getDirector(),p.getActores(),p.getOrigen(),p.getGenero(),p.getEstreno(),p.isEnCartelera()});
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Actores;
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton Buscar;
    private javax.swing.JRadioButton Cartelera;
    private javax.swing.JTextField Director;
    private javax.swing.JButton Eliminar;
    private com.toedter.calendar.JDateChooser Estreno;
    private javax.swing.JTextField Genero;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField Origen;
    private javax.swing.JTable TablaPelicula;
    private javax.swing.JTextField Titulo;
    private javax.swing.JTextField idPelicula;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listarPeliculas;
    // End of variables declaration//GEN-END:variables




}
